<Project>
  <Import Project="Version.props" />
  <PropertyGroup>
    <RuntimeAsyncBitsPath Condition="'$(RuntimeAsyncBitsPath)' == ''">E:\runtime-async-bits</RuntimeAsyncBitsPath>
    <DotnetFscCompilerPath>$(RuntimeAsyncBitsPath)\fsc\Release\net11.0\fsc.dll</DotnetFscCompilerPath>
  </PropertyGroup>
</Project>